name: CI for NestJS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test  --watch=false --maxWorkers=2

      # Paso para construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t my-docker-image:latest .

      # Paso para iniciar sesión en Docker Hub (si usas Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      # Paso para empujar la imagen Docker a Docker Hub
      - name: Push Docker image
        run: |
          docker push chat-tasks-backend:${{github.sha}}
